from __future__ import annotations

import math
import time
from typing import Any

import torch

from baselines.common.data_adapter import PDEBatch, slice_pde_batch

from .base import BaselineModel, record_optimization_status
from .variational import (
    balgovind_covariance_1d,
    observation_residuals,
    scipy_lbfgsb,
)


class Var4DBaseline(BaselineModel):
    """Strong-constraint 4D-Var for the Burgers reconstruction window.

    The control is only ``u(t=0)``. Every later state returned to the evaluator
    is generated by the differentiable Burgers propagator, so no independent
    trajectory values or soft PDE residual are optimized.
    """

    name = "var4d"

    def build(self, config, data_spec):
        super().build(config, data_spec)
        pde = str(data_spec.get("pde", "")).lower()
        if pde != "burger":
            raise ValueError("Canonical Var4D is scoped only to Burgers sparse trajectory reconstruction")
        self.optimized_numel = _initial_state_numel(data_spec)
        self.set_backend(
            "burgers_strong_constraint_4dvar",
            "4dvar_mathematical_reference",
            fallback_used=False,
            implementation_mode_effective="canonical_math",
            implementation_source="burgers_initial_control_differentiable_dynamics_scipy_lbfgsb",
            official_import_success=False,
            official_reimplementation_success=False,
            official_alignment_level="objective",
            official_alignment_notes=(
                "Canonical strong-constraint 4D-Var: optimize only the Burgers initial state, propagate the complete "
                "window with a differentiable pseudo-spectral model, and minimize background plus multi-time "
                "observation terms with L-BFGS-B. The Burgers propagator and sparse-data adapter are task-specific."
            ),
            adapter_status="canonical_strong_constraint_4dvar",
        )
        return self

    def parameter_count(self) -> int:
        return int(self.optimized_numel)

    def parameter_storage_count(self) -> int:
        return int(self.optimized_numel)

    def fit(self, train_loader, val_loader=None):
        del train_loader, val_loader
        return {
            "status": "per_instance_strong_constraint_4dvar",
            "offline_training": False,
            "optimization_variable": "decorrelated_initial_state_increment",
            "optimizer": "scipy_L-BFGS-B",
            "optimization_budget_steps_per_sample": int(self.config.get("steps", 500)),
        }

    def predict(self, batch: PDEBatch):
        start = _synchronized_time(batch.input_fields)
        _validate_burgers_trajectory(batch, "Var4D")
        steps = int(self.config.get("steps", 500))
        observation_variance = float(self.config.get("observation_variance", 1.0))
        background_variance = float(self.config.get("background_variance", 0.01))
        correlation_length = float(self.config.get("background_correlation_length", 5.0))
        tolerance = float(self.config.get("cost_decrement_tolerance", 1e-6))
        gradient_tolerance = float(self.config.get("gradient_tolerance", 1e-8))
        substeps = int(self.config.get("dynamics_substeps", 1))

        predictions: list[torch.Tensor] = []
        statuses: list[dict[str, Any]] = []
        for item in range(batch.target_fields.shape[0]):
            sample = slice_pde_batch(batch, item)
            background = _initial_background(sample)
            covariance = balgovind_covariance_1d(
                background.shape[-1],
                variance=background_variance,
                length_scale=correlation_length,
                device=background.device,
                dtype=background.dtype,
            )
            covariance_cholesky = torch.linalg.cholesky(covariance)
            time_steps = int(sample.target_fields.shape[-2])
            final_time = float(sample.metadata.get("final_time", 1.0))
            viscosity = float(sample.metadata.get("nu", sample.metadata.get("viscosity", 0.01)))

            def physical_initial_state(control: torch.Tensor) -> torch.Tensor:
                flattened = control.reshape(-1, control.shape[-1])
                increment = flattened @ covariance_cholesky.transpose(0, 1)
                return background + increment.reshape_as(control)

            def objective(control: torch.Tensor) -> torch.Tensor:
                initial_state = physical_initial_state(control)
                trajectory = propagate_burgers_trajectory(
                    initial_state,
                    time_steps=time_steps,
                    final_time=final_time,
                    viscosity=viscosity,
                    substeps=substeps,
                )
                background_term = 0.5 * control.square().sum()
                observation_term = 0.5 * observation_residuals(trajectory, sample).square().sum()
                return background_term + observation_term / max(observation_variance, 1e-12)

            optimized_control, status = scipy_lbfgsb(
                torch.zeros_like(background),
                objective,
                max_steps=steps,
                cost_decrement_tolerance=tolerance,
                gradient_tolerance=gradient_tolerance,
            )
            optimized_initial = physical_initial_state(optimized_control)
            prediction = propagate_burgers_trajectory(
                optimized_initial,
                time_steps=time_steps,
                final_time=final_time,
                viscosity=viscosity,
                substeps=substeps,
            ).detach()
            status.update(
                {
                    "sample_index": item,
                    "optimization_variable": "decorrelated_initial_state_increment",
                    "optimized_numel": int(optimized_control.numel()),
                    "dynamics_model": "burgers_pseudospectral_imex_heun",
                    "dynamics_substeps": substeps,
                }
            )
            predictions.append(prediction)
            statuses.append(status)

        record_optimization_status(batch, statuses)
        batch.metadata.update(
            {
                "assimilation_mode": "strong_constraint_full_window",
                "assimilation_background_source": "voronoi_grid_t0_from_sparse_observations",
                "assimilation_uses_hidden_truth": False,
                "optimization_variable": "decorrelated_initial_state_increment",
                "optimized_state_shape": tuple(_initial_background(batch).shape),
                "optimization_optimizer": "scipy_L-BFGS-B",
                "optimization_budget_steps_per_sample": steps,
                "optimization_function_evaluations": sum(int(status["function_evaluations"]) for status in statuses),
                "dynamics_model": "burgers_pseudospectral_imex_heun",
                "dynamics_substeps": substeps,
                "background_covariance": "Balgovind_1d",
                "background_variance": background_variance,
                "background_correlation_length": correlation_length,
                "observation_variance": observation_variance,
            }
        )
        _synchronize(batch.input_fields)
        batch.metadata["inference_optimization_time"] = time.perf_counter() - start
        return torch.cat(predictions, dim=0)


def propagate_burgers_trajectory(
    initial_state: torch.Tensor,
    *,
    time_steps: int,
    final_time: float,
    viscosity: float,
    substeps: int = 1,
) -> torch.Tensor:
    """Differentiably integrate periodic 1-D viscous Burgers dynamics.

    Spatial derivatives use a de-aliased Fourier pseudo-spectral operator.
    Diffusion is handled implicitly and the nonlinear term by a predictor-
    corrector update, allowing the saved-data interval to be subdivided while
    retaining a compact autograd graph.
    """

    if initial_state.ndim == 4 and initial_state.shape[-2] == 1:
        initial_state = initial_state[..., 0, :]
    if initial_state.ndim != 3 or initial_state.shape[1] != 1:
        raise ValueError(f"Burgers initial state must have shape [B,1,X], got {tuple(initial_state.shape)}")
    if time_steps < 1:
        raise ValueError("Burgers trajectory must contain at least one saved time")
    internal_steps = max(int(substeps), 1)
    if time_steps == 1:
        return initial_state.unsqueeze(-2)

    spatial_size = int(initial_state.shape[-1])
    dtype = initial_state.dtype
    device = initial_state.device
    dx = 1.0 / max(spatial_size, 1)
    wave_number = 2.0 * math.pi * torch.fft.rfftfreq(spatial_size, d=dx, device=device, dtype=dtype)
    wave_number = wave_number.reshape(1, 1, -1)
    wave_number_squared = wave_number.square()
    dealias = (torch.arange(wave_number.shape[-1], device=device) <= spatial_size // 3).reshape(1, 1, -1)
    dt = float(final_time) / max(time_steps - 1, 1) / internal_steps
    diffusion_left = 1.0 + 0.5 * dt * float(viscosity) * wave_number_squared
    diffusion_right = 1.0 - 0.5 * dt * float(viscosity) * wave_number_squared

    def nonlinear_hat(state: torch.Tensor) -> torch.Tensor:
        flux_hat = torch.fft.rfft(0.5 * state.square(), dim=-1)
        return torch.where(dealias, -1j * wave_number * flux_hat, torch.zeros_like(flux_hat))

    state = initial_state
    saved = [state]
    for _ in range(time_steps - 1):
        for _ in range(internal_steps):
            state_hat = torch.fft.rfft(state, dim=-1)
            first_nonlinear = nonlinear_hat(state)
            predictor_hat = (state_hat + dt * first_nonlinear) / (
                1.0 + dt * float(viscosity) * wave_number_squared
            )
            predictor = torch.fft.irfft(predictor_hat, n=spatial_size, dim=-1)
            second_nonlinear = nonlinear_hat(predictor)
            next_hat = (
                diffusion_right * state_hat + 0.5 * dt * (first_nonlinear + second_nonlinear)
            ) / diffusion_left
            state = torch.fft.irfft(next_hat, n=spatial_size, dim=-1)
        saved.append(state)
    return torch.stack(saved, dim=-2)


def _initial_state_numel(data_spec: dict) -> int:
    target_shape = tuple(int(value) for value in data_spec.get("target_shape", ()))
    if len(target_shape) != 4:
        return 0
    return int(target_shape[1] * target_shape[-1])


def _initial_background(batch: PDEBatch) -> torch.Tensor:
    _validate_burgers_trajectory(batch, "Var4D")
    guess = batch.metadata.get("voronoi_grid", batch.input_fields)
    if not isinstance(guess, torch.Tensor) or tuple(guess.shape) != tuple(batch.target_fields.shape):
        raise ValueError(
            "Burgers Var4D requires an observation-derived Voronoi T x X field with shape "
            f"{tuple(batch.target_fields.shape)}; got {getattr(guess, 'shape', None)}"
        )
    return guess[:, :, 0, :].detach().clone()


def _validate_burgers_trajectory(batch: PDEBatch, method: str) -> None:
    if batch.pde_name.lower() != "burger" or batch.target_fields.ndim != 4:
        raise ValueError(f"{method} requires a Burgers [B,1,T,X] trajectory")
    if not bool(batch.metadata.get("supports_trajectory", False)):
        raise ValueError(f"{method} requires the complete loaded Burgers trajectory contract")


def _synchronize(reference: torch.Tensor) -> None:
    if reference.device.type == "cuda" and torch.cuda.is_available():
        torch.cuda.synchronize(reference.device)


def _synchronized_time(reference: torch.Tensor) -> float:
    _synchronize(reference)
    return time.perf_counter()
